//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaluwinShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            ImagePro = "~/Content/assets/img/logo/cute.jpg";
        }
    
        public int ProductID { get; set; }
        [DisplayName("Tên sản phẩm")]
        public string NamePro { get; set; }
        [DisplayName("Mô tả")]
        public string DecriptionPro { get; set; }
        public string IDcate { get; set; }
        [DisplayName("Giá")]
        [DisplayFormat(DataFormatString = "{0:C0}")]
        public Nullable<decimal> Price { get; set; }
        [DisplayName("Hình ảnh")]
        public string ImagePro { get; set; }
        public Nullable<int> Quantity { get; set; }

        public virtual Category CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
    }
}
